# Generated by Django 5.1.4 on 2025-01-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryHistory',
        ),
        migrations.DeleteModel(
            name='UploadedData',
        ),
    ]
