name: Build and deploy Python app to Azure Web App - data-Analysis-app
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Collect static files
        run: |
          cd backend
          python manage.py collectstatic --noinput
          
      - name: Create deployment package
        run: |
          cd backend
          # Zip everything in the backend directory, including requirements.txt
          zip -r ../deploy.zip .
          
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
      - name: Unzip artifact for deployment
        run: unzip deploy.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F8799FB5C4824B9488BE7239E23ABA64 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2FE77590E50A4EDD93FF05639C0C3CD4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E904555E146248969BDADE2750D165B5 }}
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'data-Analysis-app'
          slot-name: 'Production'
          package: .